### PR TITLE
Update project to work with swift 1.2

### PR DESCRIPTION
**Pull request by rromanchuk**

### CODE REVIEW

**Comment by rromanchuk** [comment]
Compiles, and confirmed tests are passing

**Comment by PGLongo** [comment]
@michaelarmstrong SuperRecord doesn't compile with SDK 8.2. 

Swift 1.2 will be released with SDK 8.3 so I think you should revert master and support Swift 1.2 in another branch.

**Comment by rromanchuk** [comment]
Sorry, bad pull request,  i meant to merge this into a topic branch for swift 1.2 as @PGLongo  mentioned

**Comment by michaelarmstrong** [comment]
ah crap... PGLongo, you're now contributor. Please could you go ahead and revert (i'm at work now).

**Comment by michaelarmstrong** [comment]
mind you, looking at the code, it looks very backwards compatible, as its just some casts and explicitness. Does it not work in todays Xcode?

**Comment by PGLongo** [comment]
@rromanchuk  I have reverted the master. Can you make another PR to this branch feature/Swift1.2 ?

**Comment by ikesyo** [comment]
@michaelarmstrong Failable casts (`as!` operator) is a Swift 1.2 only thing. For better compatibility, we can use `(result as? NSManagedObject)!` pattern.

**Pull request merged**
