### PR TITLE
Swift 2.0

### PR DESCRIPTION
**Pull request by rromanchuk**

### CODE REVIEW

**Comment by PGLongo** [comment]
Thanks for your work. Have you run unit-tests? 

I have an **EXC_BAD_INSTRUCTION** in **testAvgGroupBy**

**Comment by rromanchuk** [comment]
Let me investigate, I'll rebase and resubmit.

**Comment by rromanchuk** [comment]
Digging into the stack it looks like we're running into a bizarre ios9 coredata issue related to this https://openradar.appspot.com/22047995

The actual error is with the persistent store. I have to look into the setup flow, but there is definitely a swift2.0/ios9 regression happening here. 
`SQLite error code:522, 'not an error' with userInfo`

**Comment by PGLongo** [comment]
I tried  to upgrade SuperRecord to Swift 2.0 but I have got the same error. I can't merge this PR or another if the tests don't pass

**Comment by michaelarmstrong** [comment]
i want to get this merged in ASAP so will be taking a look myself and trying to resolve any issues first. A new Xcode beta is out...

**Comment by michaelarmstrong** [comment]
im gonna push this to a branch on the main repo, as i'm working off this branch right now to get it working.

**Pull request merged**
