### PR TITLE
Add `includesPropertyValues` default parameter to `findAllWithPredicate`...

### PR DESCRIPTION
**Pull request by ikesyo**
..., use it in `deleteAll`

Property values are not necessary for deleting.

### CODE REVIEW

**Comment by PGLongo** [comment]
@michaelarmstrong?

**Comment by michaelarmstrong** [comment]
Please merge in the latest develop into this branch so we can merge.

**Comment by ikesyo** [comment]
Should I need do something? #16 was reverted and it can be merged now.

**Comment by ikesyo** [comment]
Thanks :wink:

**Comment by PGLongo** [comment]
Thanks to you!

**Pull request merged**
